### PR TITLE
Feature/no ref/resume

### PR DESCRIPTION
**Pull request by andyCLY**
no special, see commit, outdated

### CODE REVIEW

**Review by tranvnhan — APPROVED** [review]

**Comment by tranvnhan** [comment]
@andyCLY Could you add the description for this PR? After that, it can be merged.

**Comment by andyCLY** [comment]
> @andyCLY Could you add the description for this PR? After that, it can be merged.

the description is added on the new branch

**Comment by tranvnhan** [comment]
> > @andyCLY Could you add the description for this PR? After that, it can be merged.
> 
> the description is added on the new branch

image
I mean this one. It it for future reference.

**Comment by tranvnhan** [comment]
Close since changes will be applied on PR #8

**Pull request closed without merging**
